services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    restart: always
    volumes:
      - ./mongo:/data/db

  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo
    restart: always